FROM ubuntu:24.04

RUN yes | unminimize
RUN apt-get update \
    && apt-get install -y \
        curl \
        git \
        jq \
        man \
        openssh-server \
        python3 \
        python3-venv \
        tmux \
        vim \
        neovim \
        zsh
