FROM ubuntu:24.04

RUN yes | unminimize
RUN apt-get update \
    && apt-get install -y \
        curl \
        git \
        jq \
        man \
        openssh-server \
        python3 \
        python3-venv \
        tmux \
        vim \
        neovim \
        zsh

RUN adduser michael --disabled-password
RUN adduser michael sudo

ADD build/upstream.git/ /dotfiles/upstream.git
ADD build/plugins/ /dotfiles/plugins
RUN chown -R michael:michael /dotfiles/

ENV DOTFILES_INSTALL=0
ENV DOTFILES_PLUGIN_UPDATE=1
ENV DOTFILES_PLUGIN_SOURCE=/dotfiles/plugins
ENV DOTFILES_UPSTREAM=/dotfiles/upstream.git

