FROM distro-base:u2404

USER michael
WORKDIR /home/michael

#RUN mkdir -p /home/michael/.ssh && chmod 700 /home/michael/.ssh
#ADD known_hosts /home/michael/.ssh/known_hosts

RUN git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME init \
    && git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME remote add origin /dotfiles/upstream.git \
    && git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME fetch \
    && git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME/ checkout main

RUN zsh -i -c cat
CMD ["zsh", "-i", "-l"]
