#!/usr/bin/env bash

set -euo pipefail

DISTRO=u2404
cd "$(dirname $0)"

if ! docker inspect distro-base:${DISTRO} >/dev/null ; then
    ./common_u2404_base
fi

docker build . -f Dockerfile.home -t dotfiles:${DISTRO}
