#!/usr/bin/env bash

set -euo pipefail
source ~/lib/lister.bash

lister_cache_file "$(dirname $0)/lister.data"

lister_fields letter color number yesno

lister_fetch() {
    echo "This lister doens't support fetching." >&2
    exit 1
}

lister "${@}"
